spring:
  datasource:
    dynamic:
      primary: test
      datasource:
        test:
          url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
          type: com.alibaba.druid.pool.DruidDataSource
  flyway:
    enabled: false
    encoding: UTF-8
    locations: classpath:/db.migration.mysql
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    validate-on-migrate: true
    baseline-on-migrate: true #如果是项目中途使用flyway,配置true